eStore/Controllers/OrderController.cs
using BusinessLayer;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class OrderController : Controller
    {
        IOrderServices orderServices = null;

        public OrderController() => orderServices = new OrderServices();
        // GET: OrderController
        public ActionResult Index()
        {
            return View(orderServices.GetList());
        }

        public ActionResult Search(DateTime start, DateTime end)
        {
            if (start == null || end == null)
            {
                return View("Index", orderServices.GetList());
            }
            return View("Index", orderServices.SearchByDate(start, end));
        }

        // GET: OrderController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = orderServices.GetOrder(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // GET: OrderController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderServices.AddOrder(order);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = orderServices.GetOrder(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Order order)
        {
            try
            {
                if (id != order.OrderId)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    orderServices.UpdateOrder(order);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(order);
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = orderServices.GetOrder(id.Value);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                orderServices.DeleteOrder(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

eStore/Controllers/OrderDetailController.cs
using BusinessLayer;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace eStore.Controllers
{
    public class OrderDetailController : Controller
    {
        IOrderDetailServices orderDetailServices = null;

        public OrderDetailController() => orderDetailServices = new OrderDetailServices();
        // GET: OrderDetailController
        public ActionResult Index(int? orderId)
        {
            if (orderId == null)
            {
                return View(orderDetailServices.GetList());
            }
            return View(orderDetailServices.GetListFromOrder(orderId.Value));
        }

        // GET: OrderDetailController/Details/5
        public ActionResult Details(int orderId, int productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }
            var orderDetail = orderDetailServices.GetOrderDetail(orderId, productId);
            if (orderDetail == null)
            {
                return NotFound();
            }
            return View(orderDetail);
        }

        // GET: OrderDetailController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderDetailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderDetail orderDetail)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    orderDetailServices.AddOrderDetail(orderDetail);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderDetail);
            }
        }

        // GET: OrderDetailController/Edit/5
        public ActionResult Edit(int? orderId, int? productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }
            var orderDetail = orderDetailServices.GetOrderDetail(orderId.Value, productId.Value);
            if (orderDetail == null)
            {
                return NotFound();
            }
            return View(orderDetail);
        }

        // POST: OrderDetailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? orderId, int? productId, OrderDetail orderDetail)
        {
            try
            {
                if (orderId != orderDetail.OrderId || productId != orderDetail.ProductId)
                {
                    return NotFound();
                }
                orderDetailServices.UpdateOrderDetail(orderDetail);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(orderDetail);
            }
        }

        // GET: OrderDetailController/Delete/5
        public ActionResult Delete(int? orderId, int? productId)
        {
            if (orderId == null || productId == null)
            {
                return NotFound();
            }
            var orderDetail = orderDetailServices.GetOrderDetail(orderId.Value, productId.Value);
            if (orderDetail == null)
            {
                return NotFound();
            }
            return View(orderDetail);
        }

        // POST: OrderDetailController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int orderId, int productId, OrderDetail orderDetail)
        {
            try
            {
                orderDetailServices.DeleteOrderDetail(orderId, productId);
                return RedirectToAction(nameof(Index), orderId);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
    }
}

eStore/Views/Order/Create.cshtml
@model DataAccess.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <input asp-for="MemberId" class="form-control" />
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eStore/Views/Order/Delete.cshtml
@model DataAccess.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

eStore/Views/Order/Details.cshtml
@model DataAccess.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequiredDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Freight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Freight)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id=Model.OrderId }) |
    @Html.ActionLink("Details", "Index", "OrderDetail", new { orderId=Model.OrderId }) |
    <a asp-action="Index">Back to List</a>
</div>

eStore/Views/Order/Edit.cshtml
@model DataAccess.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <input asp-for="OrderId" class="form-control" />
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <input asp-for="MemberId" class="form-control" />
                <span asp-validation-for="MemberId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RequiredDate" class="control-label"></label>
                <input asp-for="RequiredDate" class="form-control" />
                <span asp-validation-for="RequiredDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippedDate" class="control-label"></label>
                <input asp-for="ShippedDate" class="form-control" />
                <span asp-validation-for="ShippedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Freight" class="control-label"></label>
                <input asp-for="Freight" class="form-control" />
                <span asp-validation-for="Freight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eStore/Views/Order/Index.cshtml
@model IEnumerable<DataAccess.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Orders</h1>
<form asp-action="Search" asp-controller="Order" class="form-check-inline">
    <div class="form-group my-1">
        <input class="form-control" type="datetime-local"
            name="start"/>
        <input class="form-control" type="datetime-local"
            name="end"/>
    </div>
    <div class="form-group my-1">
        <input type="submit" value="Submit" class="btn btn-primary"/>
    </div>
</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MemberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequiredDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShippedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Freight)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MemberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RequiredDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShippedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Freight)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.OrderId }) |
                @Html.ActionLink("Details", "Details", new { id=item.OrderId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.OrderId })
            </td>
        </tr>
}
    </tbody>
</table>